// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_video_cut/test/app/modules/home/domain/use_cases/pick_video_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:flutter_video_cut/app/modules/home/domain/services/gallery_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GalleryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryService extends _i1.Mock implements _i2.GalleryService {
  MockGalleryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.File?> pickVideo() =>
      (super.noSuchMethod(Invocation.method(#pickVideo, []),
          returnValue: Future<_i4.File?>.value()) as _i3.Future<_i4.File?>);
}
